'use strict';
const express=require('express'); const path=require('path');
const app=express(); const PORT=process.env.PORT||3000; const TOKEN=process.env.SELLERCHAMP_TOKEN||''; const APP_PIN=process.env.APP_PIN||''; const SC='https://app.sellerchamp.com';
app.use(express.json({limit:'500kb'})); app.use(express.static(path.join(__dirname,'public')));
function guard(req,res,next){if(!TOKEN)return res.status(503).json({error:'SELLERCHAMP_TOKEN is not configured on the server.'}); if(APP_PIN && (req.get('x-app-pin')||'')!==APP_PIN)return res.status(401).json({error:'Incorrect app PIN.'}); next();} app.use('/api',guard);
async function scFetch(ep,opt={}){const r=await fetch(SC+ep,{...opt,headers:{Token:TOKEN,'Content-Type':'application/json',...(opt.headers||{})}}); const t=await r.text(); let d={};try{d=t?JSON.parse(t):{}}catch{d={raw:t}} if(!r.ok){const e=new Error(`SellerChamp returned ${r.status}`);e.status=r.status;e.data=d;throw e}return d}
function n(v){return Number(v||0)}
async function legacyByCode(code){const q=encodeURIComponent(code); const eps=[`/api/products.json?sku=${q}&page=1&page_size=50`,`/api/products.json?catalog_sku=${q}&page=1&page_size=50`,`/api/products.json?upc=${q}&page=1&page_size=50`]; for(const ep of eps){try{const d=await scFetch(ep); const a=d.products||[]; if(a.length){const lc=String(code).toLowerCase(); const p=a.find(x=>[x.sku,x.custom_catalogue_sku,x.catalog_sku,x.upc].some(v=>String(v||'').toLowerCase()===lc))||a[0]; let locations=[];try{const ld=await scFetch(`/api/products/${encodeURIComponent(p.id)}/inventory_locations`);locations=ld.inventory_locations||[]}catch{} return {id:p.id,sku:p.sku||'',catalogue_sku:p.custom_catalogue_sku||p.catalog_sku||'',title:p.title||'',image:p.product_images?.[0]?.large_image_url||'',quantity_available:n(p.quantity_available),bin_location:p.bin_location||'',locations:locations.map(x=>({id:x.id,location:x.location||'',quantity_available:n(x.quantity_available)}))};}}catch(e){if(![400,404,422].includes(e.status))throw e}} return null}
function statusFor(line,product){const pending=n(line.quantity_pending); const loc=String(line.location||'').trim(); if(!product)return {key:'no_product',label:'Product not found',safe:false}; if(!loc)return {key:'no_location',label:'Batch location missing',safe:false}; if(pending<=0)return {key:'received',label:'Already received',safe:false}; const at=(product.locations||[]).find(x=>String(x.location).toLowerCase()===loc.toLowerCase()); if(at && n(at.quantity_available)>0)return {key:'review',label:'Inventory already exists — review',safe:false}; return {key:'safe',label:'Ready to receive',safe:true};}
app.get('/api/status',async(req,res)=>{try{await scFetch('/api/marketplace_accounts');res.json({ok:true,version:'1.0.0',pinRequired:!!APP_PIN})}catch(e){res.status(e.status||500).json({error:'Could not connect to SellerChamp.',details:e.data||e.message})}});
app.get('/api/batches',async(req,res)=>{try{const d=await scFetch('/api/master_product_batches?status=active&sort=updated_at&direction=desc&page=1&page_size=250');res.json({batches:d.master_product_batches||[]})}catch(e){res.status(e.status||500).json({error:'Could not load SellerChamp batches.',details:e.data||e.message})}});
app.get('/api/batches/:id',async(req,res)=>{try{const d=await scFetch(`/api/master_product_batches/${encodeURIComponent(req.params.id)}`); const b=d.master_product_batch||d; const lines=[]; for(const line of (b.lines||[])){let product=null;try{product=await legacyByCode(line.catalogue_sku||line.upc||'')}catch{} lines.push({...line,quantity:n(line.quantity),quantity_received:n(line.quantity_received),quantity_pending:n(line.quantity_pending),quantity_available:n(line.quantity_available),product,bridge_status:statusFor(line,product)});} res.json({batch:{...b,lines}})}catch(e){res.status(e.status||500).json({error:'Could not load this batch.',details:e.data||e.message})}});
app.put('/api/batches/:id/receive-line',async(req,res)=>{const {lineId,quantity,location}=req.body||{}; const qty=n(quantity); if(!lineId||!Number.isInteger(qty)||qty<=0||!String(location||'').trim())return res.status(400).json({error:'Line, positive whole quantity, and location are required.'}); try{const body={receive_line_ids:[lineId],receive_quantities:{[lineId]:qty},receive_locations:{[lineId]:String(location).trim()}}; const d=await scFetch(`/api/master_product_batches/${encodeURIComponent(req.params.id)}/receive`,{method:'PUT',body:JSON.stringify(body)});res.json({ok:true,result:d})}catch(e){res.status(e.status||500).json({error:'SellerChamp could not receive this inventory.',details:e.data||e.message})}});
app.put('/api/batches/:id/receive-safe',async(req,res)=>{const {lines}=req.body||{}; if(!Array.isArray(lines)||!lines.length)return res.status(400).json({error:'There are no safe lines to receive.'}); const ids=[],qs={},ls={}; for(const x of lines){if(!x.lineId||!Number.isInteger(Number(x.quantity))||Number(x.quantity)<=0||!String(x.location||'').trim())continue;ids.push(x.lineId);qs[x.lineId]=Number(x.quantity);ls[x.lineId]=String(x.location).trim()} if(!ids.length)return res.status(400).json({error:'There are no valid safe lines to receive.'}); try{const d=await scFetch(`/api/master_product_batches/${encodeURIComponent(req.params.id)}/receive`,{method:'PUT',body:JSON.stringify({receive_line_ids:ids,receive_quantities:qs,receive_locations:ls})});res.json({ok:true,received:ids.length,result:d})}catch(e){res.status(e.status||500).json({error:'SellerChamp could not receive the safe inventory lines.',details:e.data||e.message})}});
app.get('/api/product/:code',async(req,res)=>{try{const p=await legacyByCode(req.params.code);if(!p)return res.status(404).json({error:'Product not found.'});res.json({product:p})}catch(e){res.status(e.status||500).json({error:'Product lookup failed.',details:e.data||e.message})}});
app.listen(PORT,()=>console.log(`SellerChamp Inventory Bridge v1.0.0 on ${PORT}`));
